from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_dashboard, name='admin_dashboard'),
    path('login/', views.admin_login, name='admin_login'),
    path('api/metrics/', views.admin_metrics, name='admin_metrics'),
    path('api/users/', views.admin_users_list, name='admin_users_list'),
    path('api/pending-verifications/', views.admin_pending_verifications, name='admin_pending_verifications'),
    path('api/approve-user/<int:user_id>/', views.admin_approve_user, name='admin_approve_user'),
    path('api/logs/', views.admin_logs_list, name='admin_logs_list'),
    path('api/helpdesk/all/', views.admin_helpdesk_list, name='admin_helpdesk_list'),
    path('api/helpdesk/open/<int:ticket_id>/', views.admin_helpdesk_open, name='admin_helpdesk_open'),
    path('api/helpdesk/reject/<int:ticket_id>/', views.admin_helpdesk_reject, name='admin_helpdesk_reject'),
    path('api/helpdesk/resolve/<int:ticket_id>/', views.admin_helpdesk_resolve, name='admin_helpdesk_resolve'),
    path('api/diseases/', views.admin_diseases_list, name='admin_diseases_list'),
    path('api/diseases/add/', views.admin_disease_add, name='admin_disease_add'),
    path('api/diseases/edit/<int:disease_id>/', views.admin_disease_edit, name='admin_disease_edit'),
    path('api/diseases/delete/<int:disease_id>/', views.admin_disease_delete, name='admin_disease_delete'),
    path('api/users/delete/<int:user_id>/', views.admin_user_delete, name='admin_user_delete'),
    path('api/logs/delete/<int:log_id>/', views.admin_log_delete, name='admin_log_delete'),
    path('api/helpdesk/delete/<int:ticket_id>/', views.admin_helpdesk_delete, name='admin_helpdesk_delete'),
    path('api/medicines/', views.admin_medicines_list, name='admin_medicines_list'),
    path('api/medicines/add/', views.admin_medicine_add, name='admin_medicine_add'),
    path('api/medicines/edit/<int:medicine_id>/', views.admin_medicine_edit, name='admin_medicine_edit'),
    path('api/medicines/delete/<int:medicine_id>/', views.admin_medicine_delete, name='admin_medicine_delete'),
    path('api/reports/', views.admin_reports_list, name='admin_reports_list'),
    path('api/reports/add/', views.admin_report_add, name='admin_report_add'),
    path('api/reports/edit/<int:report_id>/', views.admin_report_edit, name='admin_report_edit'),
    path('api/reports/delete/<int:report_id>/', views.admin_report_delete, name='admin_report_delete'),
]
