# Generated by Django 4.2.30 on 2026-07-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'helpdesk_tickets',
            },
        ),
    ]
