# Generated by Django 4.2.30 on 2026-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_helpdeskticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskticket',
            name='status',
            field=models.CharField(default='requested', max_length=20),
        ),
    ]
