# Generated by Django 4.2.30 on 2026-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_helpdeskticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='reply',
        ),
    ]
