# Generated by Django 4.2.30 on 2026-07-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_helpdeskticket_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
    ]
