# Generated by Django 4.2.30 on 2026-07-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
