# Generated by Django 4.2.30 on 2026-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_activitylog_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('doctor', 'Doctor'), ('pharmacy', 'Pharmacy'), ('admin', 'Admin')], default='citizen', max_length=20),
        ),
    ]
