# Generated by Django 4.2.30 on 2026-07-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
