# Generated by Django 4.2.30 on 2026-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checkout_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='closes_from',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='open_from',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
