# Generated by Django 4.2.30 on 2026-08-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
