# Generated by Django 4.2.30 on 2026-08-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_age_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='appointment_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='appointment_slot_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
