# Generated by Django 4.2.30 on 2026-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='complications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
