# Generated by Django 4.2.30 on 2026-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_disease_causes_disease_complications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
