# Generated by Django 4.2.30 on 2026-08-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_userprofile_age_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'citizen_reports',
            },
        ),
        migrations.CreateModel(
            name='CitizenReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('min', models.CharField(blank=True, default='', max_length=50)),
                ('max', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='citizens.citizenreport')),
            ],
            options={
                'db_table': 'citizen_report_parameters',
            },
        ),
    ]
