# Generated by Django 4.2.30 on 2026-08-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Booked', max_length=50),
        ),
    ]
