# Generated by Django 4.2.30 on 2026-08-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomReport',
        ),
    ]
