# Generated by Django 4.2.30 on 2026-08-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_admin', '0002_delete_customreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters_json', models.TextField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'custom_reports',
            },
        ),
    ]
