# Generated by Django 4.2.30 on 2026-08-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('male_min', models.CharField(blank=True, default='', max_length=50)),
                ('male_max', models.CharField(blank=True, default='', max_length=50)),
                ('female_min', models.CharField(blank=True, default='', max_length=50)),
                ('female_max', models.CharField(blank=True, default='', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='custom_admin.report')),
            ],
            options={
                'db_table': 'report_parameters',
            },
        ),
        migrations.DeleteModel(
            name='CustomReport',
        ),
    ]
