# Generated by Django 4.2.30 on 2026-08-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_report_reportparameter_delete_customreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
