# Generated by Django 4.2.30 on 2026-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('drops', 'Drops'), ('other', 'Other')], default='tablet', max_length=50)),
                ('pack_size', models.IntegerField(default=10)),
                ('uses', models.TextField()),
                ('side_effects', models.TextField()),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
