# Generated by Django 4.2.30 on 2026-07-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pack_size',
            field=models.CharField(default='10 Tablets', max_length=100),
        ),
    ]
